/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['gzipme.js']) {
  _$jscoverage['gzipme.js'] = [];
  _$jscoverage['gzipme.js'][1] = 0;
  _$jscoverage['gzipme.js'][4] = 0;
  _$jscoverage['gzipme.js'][9] = 0;
  _$jscoverage['gzipme.js'][10] = 0;
  _$jscoverage['gzipme.js'][11] = 0;
  _$jscoverage['gzipme.js'][12] = 0;
  _$jscoverage['gzipme.js'][13] = 0;
  _$jscoverage['gzipme.js'][14] = 0;
  _$jscoverage['gzipme.js'][15] = 0;
  _$jscoverage['gzipme.js'][19] = 0;
  _$jscoverage['gzipme.js'][31] = 0;
}
_$jscoverage['gzipme.js'][1]++;
var fs = require("fs"), zlib = require("zlib");
_$jscoverage['gzipme.js'][4]++;
var OPTS = {level: zlib.Z_BEST_COMPRESSION, memLevel: zlib.Z_BEST_COMPRESSION};
_$jscoverage['gzipme.js'][9]++;
var gzipme = (function (args, callback) {
  _$jscoverage['gzipme.js'][10]++;
  fs.readFile(args, (function (err, data) {
  _$jscoverage['gzipme.js'][11]++;
  var tmpPath = "./tmp/" + args;
  _$jscoverage['gzipme.js'][12]++;
  var gzPath = "./" + args + ".gz";
  _$jscoverage['gzipme.js'][13]++;
  var gz = args + ".gz";
  _$jscoverage['gzipme.js'][14]++;
  console.log(tmpPath);
  _$jscoverage['gzipme.js'][15]++;
  console.log(gzPath);
  _$jscoverage['gzipme.js'][19]++;
  callback(gz);
}));
});
_$jscoverage['gzipme.js'][31]++;
module.exports = gzipme;
_$jscoverage['gzipme.js'].source = ["var fs = require('fs')","  , zlib = require('zlib');","","const OPTS = {","    level: zlib.Z_BEST_COMPRESSION","  , memLevel: zlib.Z_BEST_COMPRESSION","};","","var gzipme = function(args, callback) {","  fs.readFile(args, function(err, data) {","    var tmpPath = \"./tmp/\" + args;","    var gzPath = \"./\" + args + \".gz\";","    var gz = args + \".gz\";","    console.log(tmpPath);","    console.log(gzPath);","    //var inStream = fs.createReadStream(tmpPath);","    //var outStream = fs.createWriteStream(dotBuildFilePath);","    //inStream.pipe(zlib.createGzip(OPTS)).pipe(outStream);","    callback(gz);","  });","  /*","  var gzip = zlib.createGzip();","  var fs = require('fs');","  var inp = fs.createReadStream('input.txt');","  var out = fs.createWriteStream('input.txt.gz');","","  inp.pipe(gzip).pipe(out);","  */","};","","module.exports = gzipme;"];
